### PR TITLE
Allow Proxies and Class-Instances as Contexts

### PR DESCRIPTION
**Pull request by neurolag**
Though this PR adds a number of features, the key feature I want to point out is the support for dynamic context-objects such as class-instances and proxy-objects.

## General
This PR adds following features
  - Support for dynamic objects such as proxy-objects and class-instances with accessors
  - Type-declarations for better accessability (especially with TypeScript)
  - Tests for the basic functionality

### Support for Dynamic Context-Objects
I was trying to create a proxy-object in order to determine which variables are being used in the specified pattern with a code similar to this:
```ts
let variables = [];
template("${a}${b}${c}", new Proxy({}, { has: () => true, get: (target, key) => { variables.push(key); return ""; } });
console.log(variables.includes("a")); // Expceted output: `true`
```

In order to provide support for this use case I changed the approach for rendering templates a tiny bit.
After merging this PR, this uce-case is covered.

This also brings some neat features like support for class-accessors:
```ts
let x = new class
{
    public seconds = 180;
    public get Minutes() { return seconds / 60 }
}

console.log(template("The test took ${Minutes} minutes", x);
```

### Type-Declarations
By providing a type-declaration file (`index.d.ts` as specified in the `package.json`-file) code-editors like vscode, atom etc. provide extended intellisense and the package will support TypeScript out of the box.

### Tests
In order to check whether the new approach works with class-instances and proxy-objects a added a small number of tests.

Would be very awesome to see these features in a new release soon.
Thanks for hearing me out

### CODE REVIEW

**Comment by pixcai** [comment]
I saw you add **Proxy** and **Template Literals** to the source code modification. The function of this library is mainly to use template string features similar to ES6 on old browers, so source code in this library cannot use ES6 features.

**Comment by neurolag** [comment]
Thanks for the rapid answer
The `Proxy` is used here to prevent the user from accessing `context` (which is the actual context-object) as seen here:
https://github.com/pixcai/es6-template-string/blob/ce322f0a428c770b5988653261c9067dc459d7c1/index.js#L28-L47

And as seen in this test-case:
https://github.com/pixcai/es6-template-string/blob/ce322f0a428c770b5988653261c9067dc459d7c1/test.js#L22-L23

We could either not care about `context` being potentially accessible or look for some sort of polyfill.
I think we sould be fine with just discarding this read-protection as it doesn't really matter whether the `context`-object is accessible or not.

**Comment by pixcai** [comment]
First, using **Proxy** will make code incompatible with old browsers.
Second, this will make the function usage inconsistent with the **Template Literals** quantity of ES6.
you changed it like this:
```js
const cls = new class {
  get name() {
    return 'Class';
  }
};
console.log(template('${name}', cls));
```
But in ES6 it like this:
```js
console.log(`${cls.name}`);
```
It's important to be consistent.

**Comment by neurolag** [comment]
Alright I get you
Sadly I couldn't find a way to get things done without the `Proxy` library.
I'll go create my own template-project.

Thanks for your help 😄

**Comment by pixcai** [comment]
The requirements you said just need to be written like this:
```js
const template = require('.');

let variables = [];
template("${p.a}${p.b}${p.c}", {
  p: new Proxy({}, {
    has: () => true,
    get: (target, key) => {
      variables.push(key);
      return ""; 
    },
});
console.log(variables.includes("a")); // output: `true`
```
```js
let x = new class
{
    public seconds = 180;
    public get Minutes() { return seconds / 60 }
}

console.log(template("The test took ${cls.Minutes} minutes", { cls: x }); // output: 3
```

**Comment by neurolag** [comment]
Sadly this doesn't cover my case.
I'm working on a converter where the user can specify the pattern of the destination-path with variables such as `${filename}`, `${workspaceFolder}`, `${dirname}` and `${extension}`.

The `workspaceFolder` is probably unknown and I need to find out whether the pattern includes the `workspaceFolder`-variable in order to ask the user to specify the `workspaceFolder`, if necessary.

However I could find a workaround for this case which looks like this:
```ts
        let variables: string[] = [];

        let context: IPatternContext = {
            basename: "",
            extension: "",
            filename: "",
            dirname: "",
            workspaceFolder: ""
        };

        template(pattern, context); // Checking whether pattern only uses valid variables

        for (let key of Object.keys(context))
        {
            delete context[key as keyof IPatternContext];

            try
            {
                template(pattern, context);
            }
            catch
            {
                variables.push(key);
            }

            context[key as keyof IPatternContext] = "";
        }

**Comment by neurolag** [comment]
I'll create a separate PR for adding a type-declaration.
Thanks for your support! ✨

**Pull request closed without merging**
